baseURL = "https://aboros98.github.io/"
languageCode = "en-us"
theme = "PaperMod"
title = "abc - blogpost"

# Additional recommended settings
paginate = 5
summaryLength = 30

[params]
# Author info (as per PaperMod requirements)
author = "Boros Andrei"
# Other params
description = "A blog about my thoughts on academic papers"
dateFormat = "January 2, 2006"
defaultTheme = "auto" # dark, light, auto
showReadingTime = true
showShareButtons = false
showPostNavLinks = true
showBreadCrumbs = false  # Set this to false to remove the breadcrumbs
showCodeCopyButtons = true
showRssButtonInSectionTermList = true

  # Home page settings
  [params.homeInfoParams]
  Title = "Welcome to my academic blog"
  Content = "Here I share my thoughts on various academic papers."

  # Social Icons
  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/aboros98"

  [[params.socialIcons]]
  name = "email"
  url = "mailto:borosandrei1998@gmail.com"

[menu]
  [[menu.main]]
  identifier = "posts"
  name = "Posts"
  url = "/"
  weight = 10

  [[menu.main]]
  identifier = "contact"
  name = "Contact"
  url = "/contact/"
  weight = 20

[markup.goldmark.renderer]
unsafe = true # Enable unsafe mode to render raw HTML

[markup.highlight]
style = "monokai" # or any other style supported by Hugo
lineNos = true
lineNumbersInTable = true
noClasses = false