baseURL = "https://aboros98.github.io/"
languageCode = "en-us"
theme = "anubis2"
title = "abc - blogpost"

[author]
name = "Boros Andrei"
email = "borosandrei1998@gmail.com"

[params]
description = "A blog about my thoughts on academic papers"
dateFormat = "January 2, 2006"

[markup.goldmark.renderer]
unsafe = true # Enable unsafe mode to have a better experience

[markup.highlight]
style = 'base16-snazzy' # Highlight.js style